bamboo_todo/urls.py
from django.contrib import admin
from django.urls import path, include
import os
import environ
from pathlib import Path 
BASE_DIR =  Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
urlpatterns = [
    path(env('ADMIN_SITE'), admin.site.urls),
    path('', include("todo_app.urls")),
]

todo_app/urls.py
from django import views
from django.urls import path 
from . import views
app_name = 'todo'
urlpatterns = [
    path('', views.ListListView.as_view(), name='index'),
    path('list/<int:list_id>/', views.ItemListView.as_view(), name='list'),
    path('list/add/', views.ListCreate.as_view(), name='list-add'),
    path('list/<int:pk>/update/', views.ListUpdate.as_view(), name="list-update"),
    path('list/<int:pk>/delete/', views.ListDelete.as_view(), name='list-delete'),
    path('list/<int:list_id>/item/add/', views.ItemCreate.as_view(), name='item-add'),
    path('list/<int:list_id>/item/<int:pk>/', views.ItemUpdate.as_view(), name='item-update'),
    path('list/<int:list_id>/item/<int:pk>/delete/', views.ItemDelete.as_view(), name='item-delete'),
]

todo_app/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


def one_week_hence():
    """
    Return 7 days after at that time create
    """
    return timezone.now() + timezone.timedelta(days=7)


class ToDoList(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def get_absolute_url(self):
        """
        Return the URL for the particular data item
        """
        return reverse('todo:list', args=[self.id])

    def __str__(self):
        """
        Standard Python way of creating a readable 
        repersentation of an object
        """
        return self.title


class TodoItem(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(default=one_week_hence)
    todo_list = models.ForeignKey(ToDoList, on_delete=models.CASCADE)

    def get_absolute_url(self):
        """"""
        return reverse(
            'todo:item-update', args=[str(self.todo_list.id), str(self.id)]
        )

    def __str__(self):
        return f"{self.title}: due {self.due_date}"

    class Meta:
        """
        Default ordering for ToDoItem record
        """
        ordering = ["due_date"]

todo_app/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import ToDoList, TodoItem
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
class ListListView(ListView):
    model = ToDoList
    template_name = 'todo_app/index.html'


class ItemListView(ListView):
    model = TodoItem
    template_name = "todo_app/todo_list.html"

    def get_queryset(self):
        """
        # Dynamic filtering #
        Restrict data which need to return. NOT OF ALL DATA
        """
        self.todo_list = get_object_or_404(ToDoList, id = self.kwargs["list_id"]) # Check if data about todo item return not exist with ToDoList db
        return TodoItem.objects.filter(todo_list=self.kwargs["list_id"])

    def get_context_data(self):
        """
        # Adding extra context #
        Adding "todo_list" and value into TodoItem
        """
        context = super().get_context_data()
        context["todo_list"] = ToDoList.objects.get(id=self.kwargs["list_id"])
        return context

class ListCreate(CreateView):
    model = ToDoList
    fields = ['title']
    def get_context_data(self):
        context = super(ListCreate, self).get_context_data()
        context["title"]="Add a new list"
        return context

class ItemCreate(CreateView):
    model = TodoItem
    fields = [
        'title',
        'description',
        'due_date', 
        'todo_list',
    ]
    def get_initital(self):
        """
        * Override to provide initial value of ItemCreate class *
        Retriv initial data for the form 
        """
        initial_data = super(ItemCreate, self).get_initial()
        todo_list = ToDoList.objects.get(id = self.kwargs["list_id"])
        initial_data["todo_list"] = todo_list
        return initial_data
    def get_context_data(self):
        """
        * Adding extra context *
        """
        context = super().get_context_data()
        todo_list = ToDoList.objects.get(id = self.kwargs["list_id"]) 
        context['todo_list'] = todo_list
        context['title'] = 'Adding new Item'
        return context
    def get_success_url(self):
        """
        Determine the URL redirect when the form is successully validated 
        """
        return reverse("todo:list", args=[self.object.todo_list_id])

class ListUpdate(UpdateView):
    model = ToDoList
    fields = [
        'title'
    ]
    success_url = reverse_lazy("todo:index")
class ItemUpdate(UpdateView):
    model = TodoItem
    fields = [
        'title',
        'description',
        'todo_list', 
        'due_date',
    ]
    def get_context_data(self):
        """
        * Adding extra context *
        Add title and todo_list info into template
        """
        context = super(ItemUpdate, self).get_context_data()
        context['title'] = 'Update Item'
        context['todo_list'] = self.object.todo_list
        return context
    def get_success_url(self):
        return reverse("todo:list", args=[self.object.todo_list_id])

class ListDelete(DeleteView):
    """"
    Use reverse_lazy > https://codereview.doctor/features/django/best-practice/reverse-lazy-vs-reverse
    """
    model = ToDoList
    success_url = reverse_lazy("todo:index")

class ItemDelete(DeleteView):
    model = TodoItem
    def get_success_url(self):
        return reverse_lazy("todo:list", args=[self.kwargs["list_id"]])
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["todo_list"]= self.object.todo_list
        return context

todo_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- BASE TEMPLATE -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'todo_app/style.css' %}">
    <title>BAMBOO TODO</title>
</head>

<body>
    <div class="">
        <h1 onclick="location.href='{% url "todo:index" %}'">
            Bamboo.To-do
        </h1>
    </div>
    <div class="">
        {% block content %}
            {% comment %} 
                Represent other html file
            {% endcomment %}
        {% endblock %}
    </div>
    <div id="footer">
         <div class="ending-footer">
           <p class="end-heading">
             Powered by <a href="https://github.com/Qiese" target="blank" style="text-decoration: none">bieehoang</a>
           </p>
         </div>
    </div>
</body>

</html>

todo_app/templates/todo_app/index.html
{% extends "base.html" %}
{% block content %}

<!-- index.html -->
{% if object_list %}
<h3>MY DAY</h3>
{% endif %}
<ul>
    {% for todolist in object_list %}
    <li>
        <div role="button" onclick=" location.href='{% url 'todo:list' todolist.id  %} '">
                {{ todolist.title }}
        </div>
    </li>
        {% empty %}
            <h4>You have no list!</h4>
        {% endfor %}
</ul>
<p>
    <input 
        value = 'Add a new planed'
        type = 'button'
        onclick="location.href='{% url 'todo:list-add' %}'"
</p>
{% endblock %}

todo_app/templates/todo_app/todo_list.html
{% extends 'base.html' %}
{% block content %}
<div class="">
    <div class="">
        <div class="">
            <h3>Planed</h3>
            <h5>{{ todo_list.title|upper }}</h5>
        </div>
        <ul>
            {% for todo in object_list %}
            <li>
                <div class="">
                    <div class="" role="button" onclick="location.href = '{% url 'todo:item-update' todo_list.id todo.id %}'">
                        {{ todo.title }}
                        ( Due {{ todo.due_date | date:"l, F, j"}} )
                    </div>
                </div>
            </li>
            {% empty %}
            <p>You don't have job have to do today!</p>
            {% endfor %}
        </ul>
        <p>
            <input 
                type="button" 
                value="Add a new task" 
                onclick="location.href='{% url 'todo:item-add' todo_list.id %}'">
            <input 
                value = "Update planed's name"
                type = "button"
                onclick = "location.href='{% url 'todo:list-update' todo_list.id %}'">
			<input 
				value = "Delete planed"
				type = "button"
				onclick = "location.href='{% url 'todo:list-delete' todo_list.id %}'">
           </p>
    </div>
</div>
{% endblock %}

todo_app/templates/todo_app/todoitem_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h3>Delete List</h3>
<p>
    Are you sure want do delete the List <i> {{ object.title }} </i>?
</p>
<form method="post">
    {% csrf_token %}
    <input 
        value = "Yes, delete"
        type = "submit">
</form>
<input 
    value = "Cancel"
    type = "button"
    onclick="location.href='{% url 'todo:index' %}'">
{% endblock %}

todo_app/templates/todo_app/todoitem_form.html
{% extends 'base.html' %}
{% block content %}
<h3>{{ title }}</h3>
<div>
    <div>
     	<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input 
				value="Save" 
				type="submit">
			<input 
				value="Cancel" 
				type="button" 
				onclick="location.href='{% url 'todo:list' todo_list.id %}'">
			{% if object %}
				<input 
					value = "Delete this item"
					type = "button"
					onclick=location.href="{% url 'todo:item-delete' todo_list.id object.id %}">
			{% endif %}
		</form>
    </div>
</div>
{% endblock %}

todo_app/templates/todo_app/todolist_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h3>Delete Item</h3>
<p>
    Are you sure when want to delete the item <i>{{ object.title }}</i>
    from the list <b>{{ todo_list.title }}</b>?
</p>
<form method="post">
    {% csrf_token %}
    <input 
        value = "Yes, delete"
        type="submit">
    <input 
        value = "Cancel"
        type = "button"
        onclick="location.href='{% url "todo:index" %}'"
</form>
{% endblock %}

todo_app/templates/todo_app/todolist_form.html
{% extends 'base.html' %}
{% block content %}
<h3>{{ title }}</h3>
<div>
    <div>
     	<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input 
				value="Save" 
				type="submit">
			<input 
				value="Cancel" 
				type="button" 
				onclick="location.href='{% url 'todo:index' %}'">
		</form>
    </div>
</div>
{% endblock %}